cinecapau/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cineflix.urls', namespace='cineflix')),
]

cineflix/urls.py
from django.contrib import admin 
from django.urls import path 
from django.conf import settings 
from django.conf.urls.static import static 
from .views import *
from . import views   

app_name = 'cineflix'

urlpatterns = [ 
    path('', views.MovieList.as_view(), name='movie_list'),
    path('detail/<int:pk>', views.MovieDetail.as_view(), name='movie_detail'),
    path('update/<int:pk>', views.MovieUpdate.as_view(), name='movie_update'),
    path('delete/<int:pk>', views.MovieDelete.as_view(), name='movie_delete'),
    path('create', movie_criate, name = 'movie_create'), 

]  
  
if settings.DEBUG: 
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cineflix/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

genre_movie = (
    ("Ação", "Ação"), 
    ("Aventura", "Aventura"), 
    ("Cinema de arte", "Cinema de arte"), 
    ("Chanchada", "Chanchada"), 
    ("Comédia", "Comédia"), 
    ("Comédia de ação", "Comédia de ação"), 
    ("Comédia de terror", "Comédia de terror"), 
    ("Comédia dramática", "Comédia dramática"), 
    ("Comédia romântica", "Comédia romântica"), 
    ("Dança", "Dança"), 
    ("Documentário", "Documentário"), 
    ("Docuficção", "Docuficção"), 
    ("Drama", "Drama"), 
    ("Espionagem", "Espionagem"), 
    ("Faroeste", "Faroeste"), 
    ("Fantasia", "Fantasia"), 
    ("Fantasia científica", "Fantasia científica"), 
    ("Ficção científica", "Ficção científica"), 
    ("Filmes com truques", "Filmes com truques"), 
    ("Filmes de guerra", "Filmes de guerra"), 
    ("Mistério", "Mistério"), 
    ("Musical", "Musical"), 
    ("Filme policial", "Filme policial"), 
    ("Romance", "Romance"), 
    ("Terror", "Terror"), 
    ("Thriller", "Thriller"), 
)

class Movie(models.Model):
    name = models.CharField('Nome', max_length=70)
    genre = models.CharField('Gênero', max_length = 35, choices = genre_movie, default = 'Ação')
    duration = models.TimeField('Duração')
    description = models.TextField('Descrição', max_length=250)
    poster = models.ImageField('foto', upload_to='images/')
    
    
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('cineflix:movie_detail', kwargs={'pk': self.pk})

cineflix/forms.py
from django import forms 
from .models import *
  
class MovieForm(forms.ModelForm): 
  
    class Meta: 
        model = Movie 
        fields = ['name', 'genre', 'duration', 'description', 'poster'] 

cineflix/views.py
import imp
from django.http import HttpResponse 
from django.shortcuts import render, redirect 
from django.views.generic import ListView, DetailView, UpdateView, DeleteView
from django.urls import reverse, reverse_lazy
from cineflix.models import Movie
from .forms import MovieForm
from django.db.models import Q




# Create your views here.

def movie_criate(request): 
  
    if request.method == 'POST': 
        form = MovieForm(request.POST, request.FILES) 
        if form.is_valid(): 
            form.save() 
            return render(request, 'cineflix/movie_success.html')

    else: 
        form = MovieForm() 
        return render(request, 'cineflix/movie_create.html', {'form' : form}) 

class MovieList(ListView):
    model = Movie
    template_name = 'cineflix/movie_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        
        movies = Movie.objects.all()
        
        if self.request.GET.get('search_box'):
            search_box = self.request.GET['search_box']
            movies = Movie.objects.filter(Q(name__icontains = search_box) | Q(genre__icontains = search_box))

        context.update({
            'object_list': movies,
            })

        return context

class MovieDetail(DetailView):
    model = Movie
    template_name = 'cineflix/movie_detail.html'


    def get_success_url(self):
        return reverse('cineflix:movie_list')

class MovieUpdate(UpdateView):
    model = Movie
    template_name = 'cineflix/movie_update.html'
    fields = '__all__'

    def get_success_url(self):
        return reverse('cineflix:movie_list')

class MovieDelete(DeleteView):
    model = Movie
    template_name = 'cineflix/movie_confirm_delete.html'
    success_url = reverse_lazy('cineflix:movie_list')

cineflix/templates/cineflix/base.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'fontawesome-free-6.1.1-web/css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <div class="central">
      <nav class="navbar fixed-top navbar-expand-lg bg-dark">
          <div class="container">
            <a class="navbar-brand text-white" href="{% url 'cineflix:movie_list' %}"><strong>CINE</strong>FLIX</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
              <ul class="navbar-nav">
                <li class="nav-item">
                  <a class="nav-link text-secondary" href="{% url 'cineflix:movie_list' %}">Listar Filmes</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link text-secondary" href="{% url 'cineflix:movie_create' %}">Cadastrar Filme</a>
                </li>
              </ul>
            </div>
          </div>
        </nav>

      <div class="container">
          <main>
              {% block content %}{% endblock %}
          </main>
      </div>
      <footer class="navbar fixed-bottom bg-dark" >
        <p class="text-center text-white w-100 align-items-center mb-1 mt-1">Desenvolvido por 
          <a href="">Jean Carlos</a>, 
          <a href="">Daniel</a>,
          <a href="">Francinaldo</a>
          <a href="">Shara</a> e 
          <a href="">Alex</a>
        </p>
      </footer>
    </div>

    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

cineflix/templates/cineflix/movie_confirm_delete.html
{% extends "cineflix/base.html" %}

{% block title %} Apagar {% endblock %}

    
    
{% block content %}	
<form method="post">{% csrf_token %}
    <p>Tem certeza que deseja remover o Filme "{{ object }}"?</p>
    <input class="btn btn-outline-danger" type="submit" value="Confirmar">
    <a class="btn btn-outline-success" href="{% url 'cineflix:movie_list' %}">Voltar</a>
</form>
{% endblock %}

cineflix/templates/cineflix/movie_create.html
{% extends "cineflix/base.html" %}
{% load widget_tweaks %}

{% block title %} Criar Filme {% endblock %}
{% block content %}

<h4 class="my-5"> Cadastrar filme </h4>

<form method = "post" enctype="multipart/form-data">{% csrf_token %}
    <div class="row">
        {% for field in form %}
                <div class="col-md-4 mb-4">
                    <label for="{{ field.name }}" class="form-label">{{ field.label }}</label>
                    {% if field.name == 'duration' %}
                        {{ field | add_class:"form-control" |attr:"type:time" }}
                    {% else %}
                        {% if field.name == 'description' %}
                            {{ field | add_class:"form-control" | attr:"rows:5" }}
                        {% else %}
                            {{ field | add_class:"form-control" }}
                        {% endif %}
                    {% endif %}
                </div>
        {% endfor %}
    </div>
    <input type="submit" class="btn btn-outline-success" value="Cadastrar">
    <a class="btn btn-outline-dark" href="{% url 'cineflix:movie_list' %}">Voltar</a>
</form>

{% endblock %}

cineflix/templates/cineflix/movie_detail.html
{% extends "cineflix/base.html" %}

{% block title %}Detalhe do filme{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-6">
            <div class="card mb-6">
                <div class="card-body">
                    <h5 class="card-title" style="text-align: center;"> {{ movie.name }}</h5>
                    <h6 class="card-subtitle mb-2 text-muted"> Gênero: {{ movie.genre }}</h6>
                    <h6 class="card-subtitle mb-2 text-muted"> Duração: {{ movie.duration }}</h6>
                    <h6 class="card-subtitle mb-2 text-muted"> Descrição {{ movie.description }}</h6>
                </div>
                <a class="btn btn-outline-primary" href="{% url 'cineflix:movie_update' movie.pk %}">Editar</a>
                <a class="btn btn-outline-danger" href="{% url 'cineflix:movie_delete' movie.pk %}">Remover</a>
                <a class="btn btn-outline-success" href="{% url 'cineflix:movie_list' %}">Voltar</a>
            </div>

        </div>
        <div class="col-md-6">
            <img class="align-center" src="{{ movie.poster.url }}" alt="" style="height: 70vh;">
        </div>
    </div>
{% endblock %}

cineflix/templates/cineflix/movie_list.html
{% extends "cineflix/base.html" %}

{% block title %}Listagem dos filmes{% endblock %}




{% block content %}
<form class="form-horizontal mb-4" action="." method="GET">
    <div class="input-group">
        <input id="search_box" name="search_box" type="text" placeholder="Informe o nome do filme ou gênero" class="form-control" autofocus="true" value="{{ request.GET.search_box }}">
        <span class="input-group-btn">
            <button type="submit" class="btn btn-default form-control" title="Clique para realizar a pesquisar">
                <i class="fa fa-search" aria-hidden="true"></i>
            </button>
        </span>
    </div>
</form>
<h5 class="text-center">FILMES CADASTRADOS</h5>
{% if object_list.count > 0 %}
    <div class="row mb-5">
        {% for movie in object_list %}
            <div class="col-md-3">
                <div class="card mb-3">
                    <img class="card-img-top" src="{{ movie.poster.url }}" alt="" style="height: 370px; width: 100%; background-size: cover; border-radius: 5px;">
                    <div class="card-body">
                        <h5 class="card-title" style="text-align: center;"> {{ movie.name }}</h5>
                        <h6 class="card-subtitle mb-2 text-muted"> Gênero: {{ movie.genre }}</h6>
                        <h6 class="card-subtitle mb-2 text-muted"> Duração: {{ movie.duration }}</h6>
                        <a class="btn btn-outline-info" href="{{ movie.get_absolute_url }} ">Detalhes</a>
                        <a class="btn btn-outline-primary" href="{% url 'cineflix:movie_update' movie.pk %}">Editar</a>
                        <a class="btn btn-outline-danger" href="{% url 'cineflix:movie_delete' movie.pk %}">Remover</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% else %}

    <p>Nenhum filme encontrado!</p>

{% endif %}

{% endblock content %}

cineflix/templates/cineflix/movie_success.html
{% extends "cineflix/base.html" %}
{% block title %} Sucesso {% endblock %}

    
    
{% block content %}	
    <h4>Filme cadastrado com sucesso!</h4>
    <a class="btn btn-outline-success" href="{% url 'cineflix:movie_list' %}">Confirmar</a>
{% endblock %}

cineflix/templates/cineflix/movie_update.html
{% extends "cineflix/base.html" %}
{% load widget_tweaks %}

{% block title %} Atualizar {% endblock %}
{% block content %}

<h4 class="my-5"> Atualizar filme </h4>

<form method = "post" enctype="multipart/form-data">{% csrf_token %}
    <div class="row">
        {% for field in form %}
                <div class="col-md-4 mb-4">
                    <label for="{{ field.name }}" class="form-label">{{ field.label }}</label>
                    {% if field.name == 'duration' %}
                        {{ field | add_class:"form-control" |attr:"type:time" }}
                    {% else %}
                        {% if field.name == 'description' %}
                            {{ field | add_class:"form-control" | attr:"rows:5" }}
                        {% else %}
                            {{ field | add_class:"form-control" }}
                        {% endif %}
                    {% endif %}
                </div>
        {% endfor %}
    </div>
    <input type="submit" class="btn btn-outline-success" value="Cadastrar">
    <a class="btn btn-outline-dark" href="{% url 'cineflix:movie_list' %}">Voltar</a>
</form>

{% endblock %}